version: "3"

services:

  database:
    image: postgres:15.3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  sftp-server:
    image: atmoz/sftp
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "2222:22"
    environment:
      - SFTP_USERS=${SFTP_USERNAME}:${SFTP_PASSWORD}:${SFTP_UID}:${SFTP_GID}:${SFTP_HOME}

  flask-app:
    image: greenjune/symportal-kitchen:flask-app
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5000:5000"
    environment:
      - CONTACT_EMAIL_ADDRESS=${CONTACT_EMAIL_ADDRESS}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_USERNAME}
      - SFTP_HOME=${SFTP_HOME}
      - SYMPORTAL_DATABASE_CONTAINER=${SYMPORTAL_DATABASE_CONTAINER}
      - SYMPORTAL_SFTP_SERVER_CONTAINER=${SYMPORTAL_SFTP_SERVER_CONTAINER}
    depends_on:
      - database

  symportal-framework:
    image: greenjune/symportal-kitchen:symportal-framework
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_USERNAME}
      - SFTP_HOME=${SFTP_HOME}
      - SYMPORTAL_DATABASE_CONTAINER=${SYMPORTAL_DATABASE_CONTAINER}
      - SYMPORTAL_SFTP_SERVER_CONTAINER=${SYMPORTAL_SFTP_SERVER_CONTAINER}
    command: >
      bash -c "./wait-for-db.sh && tail -f /dev/null"
    depends_on:
      - database
    volumes:
      - /mnt:/mnt

  nginx:
    image: greenjune/symportal-kitchen:nginx
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/symportal:/etc/nginx/certs:ro
    depends_on:
      - flask-app
